Repository sornas/lingon, pull requests merged in 2021-05, with the labels that each got.

#46 FS raceing
  src/asset/mod.rs
Labels: T-bug

#45 Add deadzone
  src/input.rs
Labels: T-bug

#48 add some functions to asset id
  src/asset/mod.rs
Labels: S-asset

#49 draw images transparent
  res/transparent.png
  src/main.rs
  src/renderer.rs
Labels: S-rendering
